### ISSUE TITLE
请问，怎么配置并启动yuan服务，望指导解答～

### ISSUE THREAD

**Issue by rocketxujia** [spmjs/yuan#18]
我需要建个spm源，按照文档readme介绍的操作，运行命令 `python manager.py` 报异常如下； 

```
[xujia@dev52 yuan]$ python manager.py
Traceback (most recent call last):
File "manager.py", line 18, in <module>
app = create_app(CONF)
File "/home/xujia/yuan/yuan/app.py", line 43, in create_app
from .views import front, account, repository, admin
File "/home/xujia/yuan/yuan/views/account.py", line 12, in <module>
from ..forms import SignupForm, SigninForm, SettingForm
File "/home/xujia/yuan/yuan/forms/__init__.py", line 5, in <module>
from .account import *
File "/home/xujia/yuan/yuan/forms/account.py", line 4, in <module>
from flask.ext.wtf import TextField, PasswordField, BooleanField
File "/usr/local/lib/python2.7/site-packages/flask/exthook.py", line 87, in load_module
raise ImportError('No module named %s' % fullname)
ImportError: No module named flask.ext.wtf.TextField
```

我还没修改ext/config.py配置，是不是配置问题引起的？还是其他问题？帮忙解答下，谢谢～

**Comment by andythink** [comment]
@sorrycc  我不小心升级了我们公司内部的源，也出现这种情况，我手动安装了'Flask-WTF<=0.8.3'、'flask-admin<=1.0.5'还是不行
```bash
给以一下reqs-pro.txt文件中，这些模块的具体版本号吧
# This requirements is for production

Flask
misaka
pygments
gevent
requests
gunicorn

# search
Whoosh
jieba

# database
Flask-SQLAlchemy

# i18n and l10n
Flask-Babel

# form support
WTForms
Flask-WTF

# mail support
Flask-Mail

# Access control
Flask-Principal

# admin site
Flask-Admin

# command line tools
Flask-Script
```
 现在很着急啊，在线等待

**Comment by lepture** [comment]
不是应该用 node 的了么？

**Comment by andythink** [comment]
spm2的源，不是node的

**Comment by sorrycc** [comment]
不会 python 啊，帮不上忙。 @lepture @lizzie 有空帮忙看看。

**Comment by andythink** [comment]
是python的

**Comment by andythink** [comment]
@lepture  请问原来spmjs.org站点是用的https://github.com/spmjs/spm-yuan这个？

**Comment by lepture** [comment]
@andythink 是的

**Comment by afc163** [comment]
明显不是。。。

**Comment by andythink** [comment]
@afc163  那spmjs.org用的是https://github.com/spmjs/yuan？ 我们公司内部是用的这个搭的源，前两天不小心更新了一下，现在跑不起来了，一开始和楼主一样报错，后来我一个个包手动安装老版本，如下：
```
  1 # This requirements is for production
  2 
  3 Flask==0.10
  4 misaka==1.0.2
  5 pygments
  6 gevent==1.0
  7 requests==2.0.0
  8 gunicorn==17.5
  9 
 10 # search
 11 Whoosh==1.8.3
 12 jieba==0.31
 13 
 14 # database
 15 Flask-SQLAlchemy==1.0
 16 
 17 # i18n and l10n
 18 Flask-Babel 0.9
 19 
 20 # form support
 21 WTForms
 22 Flask-WTF 0.8.3
 23 
 24 # mail support
 25 Flask-Mail==0.9.0
 26 
 27 # Access control
 28 Flask-Principal==0.4.0
 29 
 30 # admin site
 31 Flask-Admin==1.0.5
 32 
 33 # command line tools
 34 Flask-Script==0.6.7
```
然后这样手动安装，可以运行python manager.py  runserve了，但是浏览器你访问报如下错误：
```
[linhong@localhost yuan]$ python manager.py  runserver
 * Restarting with stat
start server at: 127.0.0.1:5000
Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/linhong/yuan/yuan/views/front.py", line 86, in home
    obj["pretty_date"] = pretty_date(datetime.strptime(obj["update_at"], '%Y-%m-%dT%H:%M:%SZ'))
KeyError: 'update_at'
127.0.0.1 - - [2015-04-01 15:51:15] "GET / HTTP/1.1" 500 412 0.076034
```
求救啊

**Comment by lepture** [comment]
已更新 https://github.com/spmjs/yuan/commits/master

**Comment by afc163** [comment]
最后一段格式乱了。

**Comment by lepture** [comment]
@afc163 什么意思？

**Comment by afc163** [comment]
README 里的格式啊。

**Comment by lepture** [comment]
@afc163 这是 @lizzie 写的。rst 里写 markdown

**Comment by andythink** [comment]
有救了，赶紧试试

![Alt text](http://d.hiphotos.baidu.com/baike/c0%3Dbaike80%2C5%2C5%2C80%2C26/sign=4655bc0971f08202399f996d2a929088/c8ea15ce36d3d5395d1e57e93887e950352ab0fd.jpg)

**Comment by lepture** [comment]
@andythink 你的那个 bug 我不知道怎么回事，可能要把之前的 index.json 之类的删掉。

**Comment by andythink** [comment]
@lepture 谢谢，我重新下载你更新后的代码，操作步骤如下

``` bash
pip install -r conf/reqs-pro.txt
mkdir etc
cp conf/base_config.py etc/config.py
python manager.py createdb

python manager.py runserver
```

然后在浏览器里访问http://127.0.0.1:5000/, 报如下错误：

```
[xiaopang@localhost yuan]$ python manager.py runserver
 * Restarting with stat
start server at: 127.0.0.1:5000
Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/xiaopang/test/yuan/yuan/views/front.py", line 151, in home
    "total_user_count": Account.query.count(),
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2643, in count
    return self.from_self(col).scalar()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2429, in scalar
    ret = self.one()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2398, in one
    ret = list(self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2441, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2456, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 938, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1070, in _execute_context
    context)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
    exc_info
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exceptio
bigcow01 (2015-04-01 19:46:36): 
n, tb=exc_tb)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1063, in _execute_context
    context)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) no such table: account u'SELECT count(*) AS count_1 \nFROM (SELECT account.id AS account_id, account.name AS account_name, account.email AS account_email, account.password AS account_password, account.screen_name AS account_screen_name, account.description AS account_description, account.comment_service AS account_comment_service, account.role AS account_role, account.created AS account_created \nFROM account) AS anon_1' ()
127.0.0.1 - - [2015-04-01 19:45:04] "GET / HTTP/1.1" 500 412 0.064815
```

**Comment by lizzie** [comment]
> OperationalError: (OperationalError) no such table: account u'SELECT count(*) AS cou...

是不是你数据库没创建好啊。`python manager.py createdb` 有报错么

**Comment by andythink** [comment]
@lizzie 执行`python manager.py createdb`命令控制台没有输出信息，就执行结束了

**Comment by andythink** [comment]
可以手动的创建这张表？

**Comment by andythink** [comment]
现在 python manager.py createdb 运行后终端里什么都不输出，好像很成功，不知道怎么破
